### ISSUE TITLE
error:  FPGA image is not set

### ISSUE THREAD

**Issue by commthu** [jmichelp/sdrsharp-bladerf#9] opened 2016-03-17 01:02 UTC
I copy all the required dll to the sdrsharp dir and modified the FrontEnds.xml as well
when i start,  popup an errorbox "FPGA image is not set"
the sdrsharp is download from http://airspy.com/download/

**Comment by jmichelp** [comment] 2016-03-17 06:16
Unless I messed up the logic here, the message simply tells you that no FPGA image has been loaded in your board.
You can solve this issue by choosing any out of those three options (option 1 being the preferred):
1. download and put the FPGA image file in one of the auto-loading location (see bladeRF wiki)
2. use bladeRF-cli.exe to flash an FPGA image (-L option)
3. open the configuration panel in SDR# and select the FPGA image

Then you can start receiving.

All three options are supposed to be working. If you picked the third one and if it's not working as intended, I'll have a look at this weekend (not very urgent as you have existing workarounds).

**Comment by commthu** [comment] 2016-03-19 08:51
Problem is solved
firstly use SDRConsole (download from http://nuand.com/) to start receive, then shut down.
then start sdrsharp to receive, then the error will not popup and can receive normally.

**Comment by jmichelp** [comment] 2016-03-20 07:42
I'm not really considering this a problem solved :) It should work with all the 3 solutions I mentioned.

**Comment by jmichelp** [comment] 2019-05-21 20:02
No other report of such issue happening. Closing the bug

**Closed as completed by jmichelp** 2019-05-21 20:02 UTC
Labels: invalid
